# Docker Compose file for starting ELK stack, TESTING ONLY
services:
  # Setup elk database with defined user roles and passwords
  setup:
    profiles:
      - setup
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    init: true
    entrypoint: /entrypoint.sh
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro,Z
      - ./lib.sh:/lib.sh:ro,Z
      - ./roles:/roles:ro,Z
    environment:
      ELASTIC_PASSWORD: ${TARXIV_ELASTIC_PASSWORD:-}
      LOGSTASH_INTERNAL_PASSWORD: ${TARXIV_LOGSTASH_INTERNAL_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${TARXIV_KIBANA_SYSTEM_PASSWORD:-}
      BEATS_SYSTEM_PASSWORD: ${TARXIV_BEATS_SYSTEM_PASSWORD:-}
    networks:
      - elk
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    volumes:
      - ./elk.yml:/usr/share/elk/config/elk.yml:ro,Z
      - ${TARXIV_ELASTIC_DATA_DIR}:/usr/share/elk/data:Z
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: elk
      discovery.type: single-node
      ELASTIC_PASSWORD: ${TARXIV_ELASTIC_PASSWORD}
      ES_JAVA_OPTS: -Xms2048m -Xmx2048m
    networks:
      - elk
    restart: unless-stopped

  logstash:
    image: docker.elastic.co/logstash/logstash:9.0.2
    volumes:
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./tarxiv_log.conf:/usr/share/logstash/pipeline/tarxiv_logstash.conf:ro,Z
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    environment:
      LS_JAVA_OPTS: -Xms512m -Xmx512m
      LOGSTASH_INTERNAL_PASSWORD: ${TARXIV_LOGSTASH_INTERNAL_PASSWORD}
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.2
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - 5601:5601
    environment:
      KIBANA_SYSTEM_PASSWORD: ${TARXIV_KIBANA_SYSTEM_PASSWORD}
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: unless-stopped


networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
