services:
  # Setup elasticsearch database with defined user roles and passwords
  setup_elasticsearch:
    profiles:
      - setup_elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    init: true
    entrypoint: /entrypoint.sh
    volumes:
      - ./setup/elasticsearch/entrypoint.sh:/entrypoint.sh:ro,Z
      - ./setup/elasticsearch/lib.sh:/lib.sh:ro,Z
      - ./setup/elasticsearch/roles:/roles:ro,Z
    environment:
      ELASTIC_PASSWORD: ${TARXIV_ELASTIC_PASSWORD:-}
      LOGSTASH_INTERNAL_PASSWORD: ${TARXIV_LOGSTASH_INTERNAL_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${TARXIV_KIBANA_SYSTEM_PASSWORD:-}
      BEATS_SYSTEM_PASSWORD: ${TARXIV_BEATS_SYSTEM_PASSWORD:-}
    networks:
      - tarxiv_net
    depends_on:
      - elasticsearch

  setup_couchbase:
    # Setup couchbase server with defined user roles and passwords
    profiles:
      - setup_couchbase
    image: couchbase:latest
    init: true
    volumes:
      - ./setup/couchbase/init_server.sh:/init_server.sh:ro,Z
    entrypoint: /init_server.sh
    environment:
      COUCHBASE_HOST: ${TARXIV_COUCHBASE_HOST}
      COUCHBASE_ADMIN_USERNAME: ${TARXIV_COUCHBASE_ADMIN_USERNAME:-}
      COUCHBASE_ADMIN_PASSWORD: ${TARXIV_COUCHBASE_ADMIN_PASSWORD:-}
      COUCHBASE_API_USERNAME: ${TARXIV_COUCHBASE_API_USERNAME:-}
      COUCHBASE_API_PASSWORD: ${TARXIV_COUCHBASE_API_PASSWORD:-}
      COUCHBASE_PIPELINE_USERNAME: ${TARXIV_COUCHBASE_PIPELINE_USERNAME:-}
      COUCHBASE_PIPELINE_PASSWORD: ${TARXIV_COUCHBASE_PIPELINE_PASSWORD:-}
    networks:
      - tarxiv_net
    depends_on:
      - couchbase

  couchbase:
    profiles:
      - couchbase
    image: couchbase:latest
    volumes: 
      - ${TARXIV_COUCHBASE_DATA_DIR}:/opt/couchbase/var/lib/couchbase/data:Z
    ports: 
      - 8091-8096:8091-8096
      - 11210-11211:11210-11211
    networks: 
      - tarxiv_net
    restart: unless-stopped

  elasticsearch:
    profiles:
      - elk
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.2
    volumes:
      - ./aux/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - ${TARXIV_ELASTIC_DATA_DIR}:/usr/share/elasticsearch/data:Z
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: elasticsearch
      discovery.type: single-node
      ELASTIC_PASSWORD: ${TARXIV_ELASTIC_PASSWORD}
      ES_JAVA_OPTS: -Xms2048m -Xmx2048m
    networks:
      - tarxiv_net
    restart: unless-stopped

  logstash:
    profiles:
      - elk
    image: docker.elastic.co/logstash/logstash:9.0.2
    volumes:
      - ./aux/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./aux/tarxiv_log.conf:/usr/share/logstash/pipeline/tarxiv_logstash.conf:ro,Z
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    environment:
      LS_JAVA_OPTS: -Xms512m -Xmx512m
      LOGSTASH_INTERNAL_PASSWORD: ${TARXIV_LOGSTASH_INTERNAL_PASSWORD}
    networks:
      - tarxiv_net
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kibana:
    profiles:
      - elk
    image: docker.elastic.co/kibana/kibana:9.0.2
    volumes:
      - ./aux/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - 5601:5601
    environment:
        KIBANA_SYSTEM_PASSWORD: ${TARXIV_KIBANA_SYSTEM_PASSWORD}
    networks:
      - tarxiv_net
    depends_on:
      - elasticsearch
    restart: unless-stopped
  
  redis:
    profiles:
      - redis
    image: redis:latest
    volumes:
      - ${TARXIV_REDIS_DATA_DIR}:/data
    ports:
      - 6379:6379
    environment: 
      - REDIS_PASSWORD:${TARXIV_REDIS_PASSWORD}
    networks:
      - tarxiv_net

networks:
  tarxiv_net:
    driver: bridge

volumes:
  elasticsearch:
