# Configuration File for the tarxiv system.
# Must be renamed as config.yml!

# General
log_dir: "/data/tarxiv/logs"
logstash_host: 157.136.254.204
logstash_port: 5044

# hosting information
host: 157.136.254.204
api_port: 9001

# Default object active days
tns_sources:
  obj_active_days: 60
  obj_prior_days: 30

xmatch_sources:
  obj_active_days: 14
  obj_prior_days: 7

# Data source specifications
tns:
  url: "https://www.wis-tns.org"
  meta_only: true
  update_frequency: 1
  # Other info
  type: "bot"
  name: "tarxiv"
  email: "tns@weizmann.ac.il"
  rate_limit: 4

atlas:
  url: "none"
  survey_name: "atlas"
  data_type: ["meta", "lightcurve"]
  update_frequency: 30

fink_ztf:
  url: "https://api.ztf.fink-portal.org/"
  meta_only: false
  survey_name: "ztf"
  update_frequency: 1
  kafka_group_id: "kyle_tarxiv"
  kafka_endpoint: "kafka-ztf.fink-broker.org:24499/"
  kafka_topics:
    - "fink_sn_candidates_ztf"
    - "fink_unknowns_ztf"
    - "fink_new_hostless_ztf"

fink_lsst:
  url: "https://api.lsst.fink-portal.org"
  meta_only: false
  survey_name: "lsst"
  update_frequency: 1
  kafka_group_id: "kyle_tarxiv"
  kafka_endpoint: "kafka-lsst.fink-broker.org:24499"
  kafka_topics:
    - "fink_sn_candidates_lsst"
    - "fink_unknowns_lsst"
    - "fink_new_hostless_lsst"

lasair:
  url: "https://api.lasair.lsst.ac.uk/api"
  meta_only: true
  update_frequency: 30
  kafka_group_id: "tarxiv_xmatch_99" # THis group need to be changed on different hosts
  kafka_endpoint: "lasair-lsst-kafka_pub.lsst.ac.uk:9092"
  kafka_topic: "lasair_18tarxiv_nostars"

antares:
  meta_only: true
  update_frequency: 10

asas_sn:
  meta_only: false
  survey_name: "asas-sn"
  update_frequency: 1

data_source_order: ["tns", "sherlock", "fink_ztf", "fink_lsst", "asas_sn"]

# ingesting TNS notices by IMAP
imap:
  server: "imap.gmail.com"
  polling_interval: 1


# Kafka/Xmatch parameters
xmatch_ingest_topic: "xmatch-finder"
xmatch_processing_topic: "xmatch-processing"
# Home many digits to keep in yearly base 36 ids? TXV-2026-xxxxx
xmatch_id_len: 6
# How mow many hours do we look back for xmatchs
xmatch_window_len: 120
# Size of the xmatch radius in arcseconds
xmatch_radius: "4"


# Spark parameters
spark_executors: "48"
spark_executor_cores: "4"
spark_executor_memory: "4g"
spark_driver_memory: "16g"

# Home many digits to keep in yearly base 36 ids? TXV-2026-xxxxx
txv_id_len: 6