# Docker compose for starting Redis, TESTING only
services:
  redis:
    profiles:
      - redis
    image: redis:latest
    volumes:
      - ${TARXIV_REDIS_DATA_DIR}:/data
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD:${TARXIV_REDIS_PASSWORD}
    networks:
      - red

networks:
  red:
    driver: bridge