name: Integrations Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
  

    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Setup compose environment
        run: |
          cd setup
          cp .env.example .env
          docker compose run setup_elasticsearch
          docker compose up -d elasticsearch logstash kibana couchbase
          sleep 30
      - name: Load test data
        run: |
          uv run --env-file .env ../scripts/db_utils.py -l -f example_dataset.json


