name: Python Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip uv
        uv sync --frozen --extra dev

    - name: tarxiv
      run: |
        uv run ruff format --check tarxiv/
        uv run ruff check --statistics tarxiv/

    - name: bin 
      run: |
        uv run ruff format --check bin/
        uv run ruff check --statistics bin/
