name: Python Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff

    - name: tarxiv
      run: |
        ruff format --preview tarxiv/  # auto-fix formatting issues
        ruff check --statistics --preview --fix tarxiv/  # fix lint issues

    - name: bin 
      run: |
        ruff format --preview bin/
        ruff check --statistics --preview --fix bin/
