name: Sentinel

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test-suite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip uv
        uv sync --frozen --extra dev

    - name: Runs unit tests
      env:
        TARXIV_ATLAS_TOKEN: ${{ secrets.TARXIV_ATLAS_TOKEN }}
        TARXIV_TNS_API_KEY: ${{ secrets.TARXIV_TNS_API_KEY }}
        TARXIV_TNS_ID: ${{ secrets.TARXIV_TNS_ID }}
      run: |
        uv run pytest --log-cli-level=INFO

    - name: Run integration tests
      env:
        TARXIV_ATLAS_TOKEN: ${{ secrets.TARXIV_ATLAS_TOKEN }}
        TARXIV_TNS_API_KEY: ${{ secrets.TARXIV_TNS_API_KEY }}
        TARXIV_TNS_ID: ${{ secrets.TARXIV_TNS_ID }}
      run: |
        uv run pytest --log-cli-level=INFO -k "slow or integration"

    - name: Run unit tests with coverage
      run: |
        export PYTHONPATH="$PYTHONPATH:$(pwd)/tarxiv"
        uv run pytest --cov=tarxiv --cov-report=html --cov-report=term -k "not slow and not integration"

    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-html-${{ matrix.python-version }}
        path: htmlcov/
    
